name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
        
    - name: Docker Setup QEMU
      uses: docker/setup-qemu-action@v3.2.0

    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v3.6.1
    
    - name: Docker Login
      uses: docker/login-action@v3.3.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Docker Metadata action
      uses: docker/metadata-action@v5.5.1
      with:
        images: v2board 
        
    - name: Build and push Docker images
      uses: docker/build-push-action@v6.7.0
      with:
            file: ./Dockerfile
            tags: ${{ steps.meta.outputs.tags }}
            labels: ${{ steps.meta.outputs.labels }}
            push: true
