name: Docker Build and Publish

on:
  workflow_dispatch:
  push:
    branches: ["dev"]
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get version
        id: get_version
        run: echo "version=$(git describe --tags --always)" >> $GITHUB_OUTPUT

      - name: Update version in app.php
        run: |
          VERSION=$(date '+%Y%m%d')-$(git rev-parse --short HEAD)
          sed -i "s/'version' => '.*'/'version' => '$VERSION'/g" config/app.php
          echo "Updated version to: $VERSION"

      - name: Build and push
        id: build-and-push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            ${{ env.REGISTRY }}/${{ github.repository_owner }}/v2board:${{ steps.get_version.outputs.version }}
            ${{ env.REGISTRY }}/${{ github.repository_owner }}/v2board:latest
          build-args: |
            BUILDKIT_INLINE_CACHE=1
